### ISSUE TITLE
400 Bad Request by cloudflare will not retry

### ISSUE THREAD

**Issue by usbpc102** [austinv11/Discord4J#375] opened 2017-11-19 14:50 UTC
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Discord4j dosen't retry on error code 400 from cloudflare.

### Steps to Reproduce
1. try to send a message
2. hope that cloudflare has a bad day

...

**Expected behavior:** Discord4j should retry the request

**Actual behavior:** Discord4j didn't retry the request

**Stacktrace (if applicable):** https://gist.github.com/usbpc102/a6057aa418f9dea39cc4030bb537ed65

**Version affected:** Discord4J v2.9.3-SNAPSHOT cb37331

**Comment by austinv11** [comment] 2017-11-20 01:53
I do not feel confident enough to automatically retry on this. Retries on 5xxs are the only ones considered "safe" as they should only ever occur temporarily. Unless the discord team confirms that something like this should be retried on I am closing this.

**Closed by austinv11** 2017-11-20 01:53 UTC
Labels: external issue

**Comment by MinnDevelopment** [comment] 2017-11-20 06:00
This is most likely not an issue on cloudflare or Discord4J. In the past we had users whose kernel corrupted outgoing packages which caused cloudflare to report 400: Bad Request due to the broken format of the original request. It is more than likely that something quite like that is happening here.

**Comment by NexAdn** [comment] 2018-02-09 15:27
Sorry to reopen this thread, but I'm getting the same issue atm on Arch Linux. Is there any known workaround or patch available?

**Comment by austinv11** [comment] 2018-02-09 15:59
Does it consistently occur or sporadically?

**Comment by NexAdn** [comment] 2018-02-09 16:05
It seems to occur sporadically. Just got it working a few minutes ago without changing any lines so I assume it's somehow on the other end of the connection or some loss of data throughout the transmission. I will report it to you if the problem occurs.

**Comment by austinv11** [comment] 2018-02-09 16:08
Yeah, unfortunately I believe its an issue with cloudflare/discord which we have no control over and retrying is not really defined as being safe in this situation. However, if the problem is persistent I will reopen this issue to be investigated more.
