### ISSUE TITLE
failed to read any guild

### ISSUE THREAD

**Issue by DefinitlyEvil** [austinv11/Discord4J#371] opened 2017-11-12 12:44 UTC
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
getGuilds() always returns empty list, and I am logging in as a normal user not a bot. 
also it throws: 
```
20:37:06.583: [INFO][Dispatch Handler][sx.blah.discord.Discord4J] - Connected to Discord Gateway v6. Receiving 2 guilds.
READY
0
20:39:53.856: [ERROR][Dispatch Handler][sx.blah.discord.Discord4J] - Unable to process JSON!
java.lang.NullPointerException
	at sx.blah.discord.handle.impl.events.guild.channel.ChannelEvent.<init>(ChannelEvent.java:31)
	at sx.blah.discord.handle.impl.events.guild.channel.message.MessageEvent.<init>(MessageEvent.java:40)
	at sx.blah.discord.handle.impl.events.guild.channel.message.MessageDeleteEvent.<init>(MessageDeleteEvent.java:33)
	at sx.blah.discord.api.internal.DispatchHandler.messageDelete(DispatchHandler.java:474)
	at sx.blah.discord.api.internal.DispatchHandler.lambda$handle$0(DispatchHandler.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to Reproduce
```java
private void run() {
        ClientBuilder b = new ClientBuilder();
        client = b.withToken("whoops")
                .registerListener(this)
                .login();
    }

    @EventSubscriber
    public void ready(ReadyEvent e) {
        System.out.println("READY");
        try {
            Thread.sleep(2000L);
        } catch (InterruptedException e1) {
        }
        List<IGuild> guilds = client.getGuilds();
        System.out.println(guilds.size());
        for(IGuild g : guilds){
            System.out.println("Guild: " + g.getName());
        }
    }
```

...

**Expected behavior:** [What was supposed to happen]
it should return 2 guilds. 
**Actual behavior:** [What actually happened]
0 returned
**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of Discord4J]
2.9.2 (lastest dev)

**Comment by decyg** [comment] 2017-11-12 12:47
By "normal user" you mean that you are using a user token and NOT a bot token taken from your application page, this is intended behaviour, D4J does not support self-bots as it is against Discords TOS, sorry. If you are using a bot token and i'm just interpreting it wrongly, my bad and feel free to correct me.

**Comment by decyg** [comment] 2017-11-12 13:15
I'm closing this as the issue is obvious, if you want to talk about it please join the D4J discord server (as mentioned in the first of the prerequisites for opening an issue)

**Closed by decyg** 2017-11-12 13:15 UTC

**Comment by DefinitlyEvil** [comment] 2017-11-12 15:52
okie thx
